### PR TITLE
caddy-gen: add support for 'no_redir_http' repos

### PR DESCRIPTION
**Pull request by BugenZhao**
Caddy 2 redirects http request to https by default, while some mirrors should not be https-only. I add a redirection blacklist for this issue.

Fix https://github.com/sjtug/mirror-docker-siyuan/issues/17

### CODE REVIEW

**Comment by BugenZhao** [comment]
The implementation will be thorny if we allow a mirror to require both `subdomain` and `no_redir_http' feature. Considering that *siyuan* may not have a need for subdomains, I'm going to remove the support for that.

**Comment by skyzh** [comment]
What about setting current `ubuntu` and `debian` to `no_redir_http` and generate `Caddyfile`?

**Review by skyzh — APPROVED** [review]
LGTM

**Comment by BugenZhao** [comment]
> What about setting current `ubuntu` and `debian` to `no_redir_http` and generate `Caddyfile`?

I will modify `lug/config.yaml`, but since we are now using a local `BASE`, this will not be reflected in `caddy/Caddyfile`.

**Pull request merged**
